local MODULE_NAME = "SkuOptions"
local L = Sku.L
local _G = _G


SkuOptions.BindTypeStrings = {
	[0] = L["ungebunden"],
	[1] = L["BOP"],
	[2] = L["BOE"],
	[3] = L["BOU"],
	[4] = L["BOQ"],
}

SkuOptions.Glossary1 = {
	["deDE"] = {
		["Routen Wörter"] = {
			"Zentralpunkt",
			"Kreuzungspunkt",
			"Startgebiet",
			"Zielgebiet",
			"Questgeber",
			"Questziel",
			"Punkt",
		},
		["Orte"] = {
			"Anleger",
			"Auktionshaus",
			"Berg",
			"Brunnen",
			"Bank",
			"Gildenbank",
			"Briefkasten",
			"Brücke",
			"Bündelpunkt",
			"Ein- und Ausgang",
			"Fahrstuhl",
			"Farmgebiet",
			"Flugpunkt",
			"Flusslauf",
			"Friedhof",
			"Gabelung",
			"Gasthaus",
			"Gasse",
			"Gebäude",
			"Gegnergebiet",
			"Gewässer",
			"Gruft",
			"Haus",
			"Höhle",
			"Instanzeingang",
			"Kirche",
			"Kreuzung",
			"Klassenlehrer",
			"Lager",
			"Meer",
			"Passage",
			"Pfad",
			"Portal",
			"Questgeber",
			"Questgebiet",
			"Rampe",
			"Reiseroute",
			"Reparieren",
			"Route",
			"Ruhepunkt",
			"Schlucht",
			"Schiff",
			"Schmiede",
			"See",
			"Spawnpunkt",
			"Spot",
			"Stadttor",
			"Stall",
			"Stallmeister",
			"Stammesgebiet",
			"Steg",
			"Strand",
			"Straße",
			"Tal",
			"Tal",
			"Tiertrainer",
			"Tiefenbahn",
			"Trainer",
			"Treffpunkt",
			"Treppe",
			"Treppenhaus",
			"Tunnel",
			"Turm",
			"Tür/Tor",
			"Übergang",
			"Überquerung",
			"Verkaufen",
			"Versammlungsstein",
			"Weg",
			"Wegpunkt",
			"Zelt",
			"Zentralerpunkt",
			"Zeppelin",
			"Scherbenwelt",
			"Nethersturm",
			"Schergrat",
			"Zangarmarschen",
			"Höllenfeuerhalbinsel",
			"Nagrand",
			"Wälder von Terokkar",
			"Schattemondtal",
			"Shattrath",
			"Azurmythosinsel",
			"Blutmythosinsel",
			"Immersangwald",
			"Geisterlande",
			"Käfig",
			"Silbermond",
		},
		["Bindewörter"] = {
			"auf",
			"bei",
			"bis",
			"da",
			"das",
			"der",
			"die",
			"direkt",
			"dort",
			"durch",
			"ein",
			"einem",
			"hier",
			"hinter",
			"im",
			"im Umkreis",
			"in",
			"in Umgebung",
			"mit",
			"nach",
			"neben",
			"über",
			"umliegend",
			"unter",
			"von",
			"vom",
			"vor",
			"zum",
			"zu",
			"zur",
			"zwischen",
		},
		["Orientierung"] = {
			"Richtung",
			"Links",
			"Rechts",
			"Oben",
			"Unten",
			"nördlich",
			"nordöstlich",
			"östlich",
			"südöstlich",
			"südlich",
			"südwestlich",
			"westlich",
			"nordwestlich",
			"drinnen",
			"draußen",
		},
		["Klassen"] = {
			"Krieger",
			"Schurke",
			"Druide",
			"Paladin",
			"Schamane",
			"Priester",
			"Hexenmeister",
			"Magier",
			"Jäger",
			"Aldor",
			"Seher",
		},
		["Gegnertypen"] = {
			"Boss",
			"Dämonen",
			"Drachkin",
			"Elementar",
			"Elite",
			"Entartung",
			"Humanoid",
			"Mechanisch",
			"Questgegner",
			"Riese",
			"Tier",
			"Untot",
			"Wildtier",
		},
		["Berufe"] = {
			"Alchemie",
			"Angeln",
			"Bergbau",
			"Erste Hilfe",
			"Ingeneur",
			"Kochen",
			"Kräuterkunde",
			"Kürschnerei",
			"Lederverarbeitung",
			"Schmied",
			"Schneiderei",
			"Spezialisierung",
			"Verzauberkunst",
		},
		["Tätigkeiten"] = {
			"Farmen",
			"Grinden",
			"Questen",
			"Reisen",
		},
		["Spezial"] = {
			"achtung",
			"Allianz",
			"Bel",
			"geheim",
			"gut zugänglich",
			"Horde",
			"Klassenquest",
			"Level",
			"privat",
			"PVE",
			"PVP",
			"Quest",
			"schlecht zugänglich",
			"Sku",
			"Stufe",
			"Versuch",
			"vorsichtig",
			"Wichtig",
			"Rettung",
			"Hilfe",
		},
		["Maßeinheiten"] = {
			"Meter",
			"Einheiten",
		},
		["Farben"] = {
			"Blau",
			"Braun",
			"Gelb",
			"Grau",
			"Grün",
			"Orange",
			"Rot",
			"Schwarz",
		},
		["Zahlen"] = {
			"Eins",
			"Zwei",
			"Drei",
			"Vier",
			"Fünf",
			"Sechs",
			"Sieben",
			"Acht",
			"Neun",
			"Zehn",
		},
	},

	["enUS"] = {
		["routes"] = {
			"central location",
			"crossing",
			"start area",
			"target area",
			"quest giver",
			"quest target",
			"point",
		},
		["locations"] = {
			"pier",
			"auction house",
			"mountain",
			"well",
			"bank",
			"guild vault",
			"postbox",
			"bridge",
			"Focus point",
			"entry and exit",
			"elevator",
			"farming area",
			"flight master",
			"river",
			"graveyard",
			"jungction",
			"inn",
			"alley",
			"building",
			"hostile area",
			"waters",
			"tomb",
			"house",
			"cave",
			"instance entrance",
			"church",
			"crossing",
			"class trainer",
			"camp",
			"ocean",
			"passage",
			"trail",
			"portal",
			"quest giver",
			"quest area",
			"ramp",
			"travel route",
			"repair",
			"route",
			"Resting location",
			"gorge",
			"ship",
			"forge",
			"lake",
			"spawn location",
			"spot",
			"city gate",
			"stable",
			"stable master",
			"tribe area",
			"jetty",
			"beach",
			"street",
			"valley",
			"valley",
			"pet trainer",
			"deep tram",
			"trainer",
			"meeting point",
			"stairway",
			"staircase",
			"tunnel",
			"tower",
			"door/gate",
			"passage",
			"traverse",
			"selling",
			"meeting stone",
			"path",
			"waypoint",
			"tent",
			"centralpoint",
			"zeppelin",
			"outland",
			"netherstorm",
			"blade's edge mountains",
			"zangarmarsh",
			"hellfire peninsula",
			"nagrand",
			"terokkar forrest",
			"shadowmoon valley",
			"shattrath",
			"azuremyst isle",
			"bloodmyst isle",
			"eversong woods",
			"ghostlands",
			"cage",
			"Silvermoon",
		},
		["connective words"] = {
			"on",
			"at",
			"to",
			"there",
			"that",
			"the",
			"the",
			"direct",
			"there",
			"through",
			"an",
			"any",
			"here",
			"behind",
			"in",
			"around",
			"in",
			"in area",
			"with",
			"to",
			"next to",
			"above",
			"surrounding area",
			"below",
			"from",
			"from",
			"before",
			"to",
			"to",
			"to",
			"between",
		},
		["orientation"] = {
			"direction",
			"left",
			"right",
			"top",
			"down",
			"north",
			"notheast",
			"east",
			"southeast",
			"south",
			"southwest",
			"west",
			"northwest",
			"inside",
			"outside",
		},
		["classes"] = {
			"warrior",
			"rogue",
			"druid",
			"paladin",
			"Shaman",
			"priest",
			"warlock",
			"mage",
			"hunter",
			"aldor",
			"scryers",
		},
		["enemy types"] = {
			"boss",
			"daemon",
			"dragonkins",
			"elementals",
			"elite",
			"aberrations",
			"humanoids",
			"mechanicals",
			"quest target",
			"giants",
			"citter",
			"Undead",
			"beasts",
		},
		["professions"] = {
			"alchemy",
			"fishing",
			"mining",
			"first aid",
			"engineering",
			"cooking",
			"herbalism",
			"skinning",
			"leatherworking",
			"blacksmithing",
			"tainloring",
			"specialization",
			"enchanting",
		},
		["activities"] = {
			"farming",
			"grinding",
			"questing",
			"traveling",
		},
		["special"] = {
			"attention",
			"alliance",
			"bel",
			"secret",
			"easily accessible",
			"horde",
			"class quest",
			"pevel",
			"private",
			"pve",
			"pvp",
			"euest",
			"pooly accessible",
			"Sku",
			"level",
			"try",
			"careful",
			"important",
			"rescue",
			"help",
		},
		["measurement units"] = {
			"meters",
			"units",
		},
		["colors"] = {
			"blue",
			"brown",
			"yellow",
			"grey",
			"green",
			"orange",
			"red",
			"black",
		},
		["numbers"] = {
			"one",
			"two",
			"three",
			"four",
			"five",
			"six",
			"seven",
			"eight",
			"nine",
			"ten",
		},
	},
}


